server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/yanjingchang/orderingsystem.git
          searchPaths: config
          username: yanjingchang
          password: Github_7920
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/